import {useMemo,useState} from 'react';
import replay from './replay.json';
import audit from './evaluation-evidence.json';
import {contracts} from './contracts';
import {evaluationReport} from './evaluation';
import {priorWork,externalProtocol} from './researchContext';
const pct=(x:number|null)=>x===null?'Not available':`${(100*x).toFixed(1)}%`;
function save(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function MatchedEvaluation(){const [index,setIndex]=useState(1);const report=useMemo(()=>evaluationReport(replay.engines,contracts[index].policy),[index]);
 return <details className="cs-research cs-audit"><summary>Compare matched cycles and separate uncertainty mechanisms</summary><label>Audit contract <select aria-label="Matched audit contract" value={index} onChange={e=>setIndex(Number(e.target.value))}>{contracts.map((c,i)=><option value={i} key={c.id}>{c.name}</option>)}</select></label><h3>Fixed cycles 30–120 · complete records only</h3><p>{report.matched.included.length} engines × 91 cycles = {report.matched.frames} snapshots. Engine 001 excluded: 2 of 91 cycles available. Included engines: {report.matched.included.map(n=>String(n).padStart(3,'0')).join(', ')}.</p><p>{report.matched.scope}</p><div className="cs-table-wrap"><table aria-label="Matched-cycle sensitivity"><thead><tr><th>Scenario</th><th>Changed / matched snapshots</th></tr></thead><tbody>{report.sensitivity?.rows.map(r=><tr key={r.name}><th scope="row">{r.name}</th><td>{r.changed} / {report.matched.frames} ({pct(r.changedFraction)})</td></tr>)}</tbody></table></div><p>Equal-engine and frame weighting coincide here because each included engine contributes 91 records. This earlier window omits later degradation and does not estimate whole-life robustness.</p><h3>Mechanism isolation · all 1,233 FD001 replay snapshots</h3><div className="cs-table-wrap"><table aria-label="Uncertainty mechanisms"><thead><tr><th>Scoring width</th><th>Eligibility width</th><th>Changed advice</th><th>Margin active</th></tr></thead><tbody>{report.mechanisms.rows.map(r=><tr key={`${r.scoreWidth}-${r.eligibilityWidth}`}><td>{r.scoreWidth}×</td><td>{r.eligibilityWidth}×</td><td>{r.changed} / {report.mechanisms.frames}</td><td>{r.gated}</td></tr>)}</tbody></table></div><p>{report.mechanisms.scope}</p><button className="cm-button" onClick={()=>save({...report,policy:contracts[index].policy,sourceHashes:replay.files,model:replay.model},'cmapss-matched-mechanisms.json')}>Export matched and mechanism evidence</button></details>;
}
export function IntervalAudit(){return <details className="cs-research cs-audit"><summary>Audit interval coverage and the 125-cycle cap</summary><p>Frozen predictions; one endpoint per test engine; all four test sets. The training-residual interval has an 80% reference level. No test labels are used to refit or change recommendations.</p><div className="cs-table-wrap"><table aria-label="Endpoint interval audit"><thead><tr><th>Subset</th><th>All endpoints covered</th><th>Truth ≤125: covered</th><th>Truth &gt;125: covered</th><th>Mean width</th></tr></thead><tbody>{audit.intervals.map(r=><tr key={r.dataset}><th scope="row">{r.dataset}</th><td>{r.all.covered}/{r.all.n} ({pct(r.all.coverage)})</td><td>{r.withinCap.covered}/{r.withinCap.n} ({pct(r.withinCap.coverage)})</td><td>{r.aboveCap.covered}/{r.aboveCap.n}</td><td>{r.all.meanWidth!.toFixed(1)} cycles</td></tr>)}</tbody></table></div><p className="cs-warning">Every truth value above 125 lies beyond the clipped upper bound. The within-cap results are conditional diagnostics, not improved overall coverage or proof of calibration. Retain uncapped truth for the primary evaluation.</p><p>Decision scoring additionally assumes a normal distribution from interval width. Endpoint coverage does not validate those action-specific probabilities. A future recalibration must use training/calibration engines and then an untouched evaluation set.</p><button className="cm-button" onClick={()=>save(audit,'cmapss-evaluation-audit.json')}>Export interval audit and provenance</button></details>}
export function ResearchPosition(){return <details className="cs-research cs-audit"><summary>Position the contribution against prior work and plan external validation</summary><p>Focused source positioning, checked 6 October 2026. This is not a systematic review or a novelty verdict. Reading scope is stated for every source; an unmentioned feature is not assumed absent.</p><div className="cs-table-wrap"><table aria-label="Prior-work positioning"><thead><tr><th>Source / reading scope</th><th>Established capability</th><th>Project position</th></tr></thead><tbody>{priorWork.map(r=><tr key={r.name}><th scope="row"><a href={r.url} target="_blank" rel="noreferrer">{r.name}</a><p>{r.basis}</p></th><td>{r.established}</td><td>{r.position}<p>{r.needed}</p></td></tr>)}</tbody></table></div><h3>External evaluation · not yet conducted</h3><p>{externalProtocol.semantic.currentStatus}</p><ol>{externalProtocol.semantic.questions.map(q=><li key={q}>{q}</li>)}</ol><p>{externalProtocol.semantic.design}</p><h3>Empirical service evidence · not yet collected</h3><p>{externalProtocol.outcomes.design}</p><p>Required records: {externalProtocol.outcomes.requiredFields.join('; ')}.</p><button className="cm-button" onClick={()=>save({sources:priorWork,...externalProtocol},'cmapss-external-evaluation-protocol.json')}>Export external evaluation protocol</button></details>}
