export const priorWork=[
 {name:'ISO 23247-2:2021',url:'https://www.iso.org/standard/78743.html',basis:'Official scope',established:'Entity-based reference model and functional view for manufacturing digital twins.',position:'This project applies responsibility groups to service advice. The architecture itself is adopted, not claimed as new.',needed:'A clause-level mapping and stakeholder evaluation; ISO conformance is not claimed.'},
 {name:'Longo, Nicoletti & Padovano (2019)',url:'https://arxiv.org/abs/2206.03268',basis:'Author abstract; 2019 journal article, deposited 2022',established:'Service-oriented DT with an ontology-oriented knowledge structure and two manufacturing test-beds.',position:'Combining service-oriented DT and ontology is prior art. Our visible focus is explicit contract assumptions and inspectable recommendation evidence.',needed:'Full-text comparison of constructs and tasks before claiming a distinctive research contribution.'},
 {name:'Nguyen, Schulte & Lindow (2025)',url:'https://doi.org/10.1007/978-3-031-93891-7_56',basis:'Publisher abstract and introduction',established:'Ontology-based turbine-blade maintenance framework connecting maintenance information; implementation and validation are future work in its abstract.',position:'A maintenance ontology/framework is prior art. Our prototype adds executable benchmark queries, checks and fixed-evidence policy comparisons within its stated scope.',needed:'Detailed modelling comparison; this scoped reading does not establish absence of equivalent methods in the literature.'},
 {name:'W3C SHACL (2017)',url:'https://www.w3.org/TR/shacl/',basis:'W3C Recommendation',established:'A standard language for validating RDF graphs against shapes.',position:'Constraint execution is an adopted capability. Candidate contribution lies in the service evidence requirements and their application, not SHACL itself.',needed:'Independent competency questions, heterogeneous sources and measured maintenance tasks.'}
];
export const externalProtocol={
 version:'0.8',status:'Not conducted; protocol and empty evidence requirements only',
 semantic:{status:'Awaiting independent reviewer and external inputs',questions:[
  'Which asset, observation, generating model and source support this recommendation?',
  'Which contract version and responsibility were actually applied?',
  'After a contract or source identifier changes, which recommendations require review?',
  'Can equivalent evidence from an independently supplied schema be mapped without loss of units or identity?'
 ],design:'Freeze requirements and expected answers before either implementation is adapted. A reviewer other than the implementation author supplies withheld fixtures. Use equal inputs, error classes and tasks for JSON and RDF. Record correctness, lost mappings, edits and reviewer effort; do not infer superiority from pass counts alone.',currentStatus:'Questions and stress tests here are project-authored. No external participant, unseen holdout or effort measurement is represented.'},
 outcomes:{status:'No empirical contract or intervention outcomes supplied',requiredFields:['pseudonymous asset ID','contract/version and authority','responsibility and cost basis','decision timestamp and available evidence','proposed action','authorised action and reviewer','actual intervention and timing','downtime/exposure measurement period','observed service outcome','comparable baseline and confounders'],design:'Define the service outcome, eligible population, observation period and baseline before collecting results. Record actual decisions and outcomes separately from proposals. Evaluate prospective data with human approval; do not use the same assumed cost formula as evidence of realised value.'},
 novelty:{status:'Focused source positioning only; not a systematic review',design:'Extend the cited source matrix with full-text methods, explicit inclusion criteria and claim-by-claim evidence. Missing information is not evidence that earlier work lacks a capability.'}
};
