import {useMemo,useState} from 'react';
import data from './replay.json';
import {contracts} from './contracts';
import {caseRoles,contributionEvidence,examinerQuestions,handoffSteps,sensitivityReport} from './viva';

export function ServiceScope(){return <div className="cs-service-scope" aria-label="Asset and service research scope"><h3>Two connected representations</h3><div><b>Asset evidence · implemented</b><p>Recorded observations → degradation prognosis → RUL evidence</p></div><div><b>Service context · implemented</b><p>Assumed obligation → provider responsibility → policy → proposed advice</p></div><div className="cs-future"><b>Service delivery · not implemented</b><p>Planner authorisation → maintenance delivery → observed outcome → feedback</p></div><p className="cs-caption">Operator: supplies the asset context. Service provider: carries assumed interruption exposure. Maintenance planner: intended reviewer; no actual approval is recorded.</p></div>}
export function Handoff({elapsed,manual}:{elapsed:number;manual:boolean}){const active=Math.min(4,Math.floor(elapsed/3500));return <div className="cs-handoff" aria-label="Implemented evidence handoff"><h3>Who owns each step, and what is exchanged?</h3><p className="cs-caption">Explanatory sequence of the implementation; not a live network trace.</p><ol>{handoffSteps.map((h,i)=><li key={h.owner} className={`${i===active&&!manual?'active':''} ${i===4?'cs-future':''}`}><b>{h.owner}</b><strong>{h.object}</strong><span>{h.check}</span></li>)}</ol><p className="cs-warning">Validation inspects existing advice. It does not currently enforce an approval gate.</p></div>}
export function Contributions(){return <div className="cs-contributions">{contributionEvidence.map(c=><article key={c.claim}><b>{c.claim}</b><p>{c.implemented}</p><p><strong>Demonstrated:</strong> {c.evidence}</p><details><summary>Still needed to support the research claim</summary><p>{c.missing}</p></details></article>)}</div>}
export function CaseComparison(){return <section className="cs-case-comparison" aria-label="Complementary case studies"><h3>Two cases, complementary research roles</h3><div>{caseRoles.map(c=><article key={c.name}><h4>{c.name}</h4><b>{c.focus}</b><p>{c.evidence}</p><small>{c.boundary}</small></article>)}</div><p className="cs-caption">Shared method: framework responsibilities + explicit semantic evidence + service decisions. These cases support different aspects; neither establishes industrial effectiveness.</p></section>}
export function ExaminerPanel({stage}:{stage:string}){const q=examinerQuestions[stage];return <details className="cs-examiner"><summary>Examiner question · {q.question}</summary><p>{q.answer}</p><p><b>Evidence still required:</b> {q.remaining}</p></details>}
export function SensitivityPanel(){
 const [selected,setSelected]=useState(0);
 const report=useMemo(()=>sensitivityReport(data.engines,contracts[selected].policy),[selected]);
 function download(){const content={...report,model:data.model,sourceHashes:data.files};const url=URL.createObjectURL(new Blob([JSON.stringify(content,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cmapss-viva-sensitivity.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <details className="cs-research"><summary>Inspect computed sensitivity and threshold-only comparison</summary><h3>How dependent is advice on the assumptions?</h3><label>Reference contract <select aria-label="Sensitivity contract" value={selected} onChange={e=>setSelected(Number(e.target.value))}>{contracts.map((c,i)=><option value={i} key={c.id}>{c.name}</option>)}</select></label><p>{report.frames.toLocaleString('en-GB')} recorded snapshots / {report.engineIds.length} selected engines · FD001 only. Computed with the same advisory function used by the story.</p><div className="cs-table-wrap"><table><thead><tr><th>One-factor scenario</th><th>Changed vs reference</th><th>Differs from threshold only</th></tr></thead><tbody>{report.rows.map(r=><tr key={r.name}><th scope="row">{r.name}</th><td>{r.changed} / {report.frames} ({(r.changedFraction*100).toFixed(1)}%)</td><td>{r.thresholdDisagreements} / {report.frames}</td></tr>)}</tbody></table></div><p>{report.comparator}</p><p>{report.perturbation}</p><p className="cs-warning">{report.scope}</p><details><summary>Decision formula and omitted mechanisms</summary><p>{report.decisionAssumptions}</p><p>Action waiting periods are illustrative: Continue 20 cycles, Monitoring 10, Inspection 5, Maintenance / Hold 0. More monitoring does not model information gain or a subsequent maintenance trajectory.</p></details><button className="cm-button" onClick={download}>Export sensitivity evidence</button></details>;
}
