"""Refit the Chapter 5 quantile models and export auditable browser inference artifacts."""
import argparse
import hashlib
import importlib.util
import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import sklearn
import xgboost as xgb

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--chapter-dir', type=Path)
parser.add_argument('--snapshot', action='store_true', help='Use the committed source and feature snapshot')
args = parser.parse_args()
chapter = args.chapter_dir or ROOT.parent / 'Chapter 5 - Demonstration (Micro Wind Turbine)'
snapshot = args.snapshot or (args.chapter_dir is None and not (chapter / 'run_pipeline.py').exists())
source = ROOT / 'models/chapter5/source-run-pipeline.py' if snapshot else chapter / 'run_pipeline.py'
dataset = ROOT / 'models/chapter5/features.csv' if snapshot else chapter / 'outputs/features.csv'
spec = importlib.util.spec_from_file_location('chapter5_pipeline', source)
pipeline = importlib.util.module_from_spec(spec)
spec.loader.exec_module(pipeline)
df = pd.read_csv(dataset)
features = pipeline.get_feature_cols(df)
assert len(features) == 31 and not {'state', 'crack_mm', 'wind_bin', 'rul_h'} & set(features)
assert np.isfinite(df[features + ['rul_h']].to_numpy()).all()
assert np.allclose(df.rul_h, pipeline.T_EOL * (1 - df.crack_mm / pipeline.A_EOL))
params = dict(n_estimators=300, max_depth=6, learning_rate=0.05,
              objective='reg:quantileerror', random_state=42, verbosity=0)

# Run the original evaluation function unchanged, then refit deployable models on all rows.
evaluation = pipeline.train_rul_xgboost(df)
evaluation = {k: v for k, v in evaluation.items() if k not in ('y_true', 'p10', 'p50', 'p90')}
out = ROOT / 'models/chapter5'
out.mkdir(parents=True, exist_ok=True)
if dataset.resolve() != (out / 'features.csv').resolve():
    shutil.copyfile(dataset, out / 'features.csv')
if source.resolve() != (out / 'source-run-pipeline.py').resolve():
    shutil.copyfile(source, out / 'source-run-pipeline.py')
models, model_hashes, predictions = {}, {}, {}
X = df[features].to_numpy(dtype=np.float32)
y = df.rul_h.to_numpy()
probes = np.concatenate([X, np.full((1, len(features)), np.nan, dtype=np.float32)])
for key, alpha in [('p10', .1), ('p50', .5), ('p90', .9)]:
    model = xgb.XGBRegressor(**params, quantile_alpha=alpha)
    model.fit(X, y)
    path = out / f'{key}.json'
    model.save_model(path)
    model_hashes[key] = hashlib.sha256(path.read_bytes()).hexdigest()
    saved = json.loads(path.read_text())['learner']
    assert saved['objective']['name'] == 'reg:quantileerror'
    booster = saved['gradient_booster']
    assert booster['name'] == 'gbtree'
    trees = booster['model']['trees']
    assert len(trees) == 300 and all(not any(t['split_type']) for t in trees)
    # Preserve only inference arrays; official full save_model exports are also committed.
    models[key] = {
        'baseScore': float(saved['learner_model_param']['base_score']),
        'trees': [{k: t[k] for k in ('left_children', 'right_children', 'split_indices', 'split_conditions', 'default_left')} for t in trees]
    }
    predictions[key] = model.predict(probes).tolist()

references = []
for (crack, wind_bin), group in df.groupby(['crack_mm', 'wind_bin'], sort=True):
    references.append({'crackMm': float(crack), 'windSpeed': float(group.wind_mean.mean()),
                       'windBin': wind_bin, 'values': group[features].mean().tolist()})
manifest = {
    'version': 'ch5-xgb-quantile-1.0', 'name': 'Chapter 5 XGBoost quantile regression',
    'objective': params['objective'], 'parameters': params, 'quantiles': [.1, .5, .9],
    'featureNames': features, 'rows': len(df), 'evaluation': evaluation,
    'evaluationScope': 'Original stratified 5-fold CV on controlled synthetic C0-C6 labels; not field lifetime validation',
    'target': '1000 * (1 - crack_mm / 80) synthetic pseudo-hours',
    'sourceHashes': {'run_pipeline.py': hashlib.sha256(source.read_bytes()).hexdigest(), 'features.csv': hashlib.sha256(dataset.read_bytes()).hexdigest()},
    'modelHashes': model_hashes,
    'runtime': {'xgboost': xgb.__version__, 'scikit-learn': sklearn.__version__, 'numpy': np.__version__, 'pandas': pd.__version__},
    'featureRanges': [{'min': float(df[c].min()), 'max': float(df[c].max())} for c in features],
    'referenceScope': 'State/wind-bin mean feature interpolation for scenarios; not measured observations',
    'calibration': 'No conformal calibration; nominal quantiles can cross or under-cover',
}
(out / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
payload = {'manifest': manifest, 'references': references, 'replayVectors': X.tolist(), 'models': models}
(ROOT / 'src/data/chapter5Xgboost.ts').write_text('// Generated by scripts/train-chapter5-xgboost.py; do not edit manually.\nexport default ' + json.dumps(payload, separators=(',', ':'), allow_nan=False) + ';\n')
fixtures = {'vectors': [[None if not np.isfinite(x) else float(x) for x in row] for row in probes],
            'predictions': predictions, 'tolerance': .001}
(out / 'python-parity.json').write_text(json.dumps(fixtures, separators=(',', ':'), allow_nan=False) + '\n')
print(json.dumps({'rows': len(df), 'features': len(features), 'evaluation': evaluation,
                  'browserArtifactBytes': (ROOT / 'src/data/chapter5Xgboost.ts').stat().st_size}, indent=2))
